config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "words#index"
  resources :users, only: :show

  resources :tests, only: [:show, :update] do
    resources :answers, only: :create
    member do
      get 'result'
    end
  end
  
  resources :words, only: [ :index, :create, :destroy, :edit, :update ] do
    resources :goods, only: [:create, :destroy]
    resources :adoptions, only: [:create, :destroy]
    
    member do
      get 'search_mydic'
    end

    collection do
      get 'search_index'
    end

    member do
      get 'order_mydic'
    end

    collection do
      get 'order_index'
    end
    
    collection do
      get 'weblio_pull'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :words, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :good_words, through: :goods, source: :word
  has_many :adoptions, dependent: :destroy
  has_many :adoption_words, through: :adoptions, source: :word
  has_many :tests

  validates :nickname, presence: true
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  def good(word)
    goods.find_or_create_by(word: word)
  end

  def good?(word)
    good_words.include?(word)
  end

  def ungood(word)
    good_words.delete(word)
  end

  def adoption(word)
    adoptions.find_or_create_by(word: word)
  end

  def unadoption(word)
    adoption_words.delete(word)
  end

  def adoption_word_create(word)
    Word.create(word)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
    @word = Word.new
    @words = @user.words.order("created_at DESC")
    @good_words = @user.good_words.order(created_at: :desc).limit(5)
    @adoption_words = @user.adoption_words.order(created_at: :desc).limit(5)
    @test = Test.new
    @tests = Test.where(user_id: current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "devise/shared/header" %>

<div class="mydic-contents">
  <div class="main">
    <div class="page-title">
      <h3><%= @user.nickname%>さんのMydicページ</h3>
    </div>
    <%# 英単語追加する部分 %>
    <% if user_signed_in? && @user.id == current_user.id%>
      <div class="new-word">
        <div class="new-word-header">
          <h3> - My dicに英単語追加 - </h3>
          <div id="pull-error" class="pull-error"></div>
        </div>
        <%= form_with model: @word, url: words_path, method: :post, class: "new-word-form", local: true do |f| %>
          <div class="important">
            <p>重要</p>
            <%= f.check_box :important, id: "important_check_box", checked: true, unchecked: false %>
          </div>
          <div class="name">
            <p>英単語</p>
            <%= f.text_area :name, class:"name-form", id:"word-name", placeholder:"英単語を入力" %>
            <div class="link-list">
              <%= submit_tag "Weblio引用", class: "weblio-link", id: "weblio-link" %>
            </div>
          </div>
          <div class="pos">
            <p>品詞</p>
            <%= f.collection_select(:pos_id, Pos.all, :id, :name, {}, {class:"select-box", id:"word-pos"}) %>
          </div>
          <div class="meaning">
            <p>和訳</p>
            <%= f.text_area :meaning, class:"meaning-form", id:"word-meaning", placeholder:"和訳を入力", rows: "3" %>
          </div>
          <div class="genre">
            <p>ジャンル</p>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"word-textgenre"}) %>
          </div>
          <div class="text">
            <p>テキスト</p>
            <%= f.text_area :text, class:"text-form", id:"word-text", placeholder:"テキストを入力（任意）", rows: "3" %>
          </div>
          <div class="publish">
            <p><%= image_tag "publish_logo.png", class:"publish-pict" %></p>
            <%= f.check_box :publish, id: "publish_check_box", checked: true, unchecked: false %>
          </div>
          <div class="new-submit">
            <%= f.submit "追加" ,class:"add-btn" %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%# 英単語一覧表示する部分 %>
    <div class="word-index">
      <div class="word-index-header">
        <h3> - My dic  一覧 - </h3>
        <div class="word-index-header-right">
          <div class="word-search">
            <%= form_with(url: search_mydic_word_path(@user.id), local: true, method: :get, class: "word-search") do |form| %>
              <%= form.text_field :keyword, placeholder: "検索ワード入力", class: "search-input" %>
              <%= form.select :condition, [['を含む', 1], ['から始まる', 2]] %>
              <%= form.select :category, [['全て', 1],['英単語', 2], ['和訳', 3], ['テキスト', 4]] %>
              <div class="search-text">を</div>
              <%= form.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
          <div class="index-sort">
            <%= form_with(url: order_mydic_word_path(@user.id), local: true, method: :get, class: "word-search") do |form| %>
              <%= form.select :condition, [['登録新しい順', 1], ['登録古い順', 2], ['英単語ｱﾙﾌｧﾍﾞｯﾄ順', 3], ['重要ワード優先', 4], ['グー数多い順', 5], ['採用数多い順', 6], ['品詞順', 7], ['ジャンル順', 8]] %>
              <%= form.submit "並び替え", class: "search-btn" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="word-index-data">
        <div class="word-contents">
          <table class="index_table">
            <%# ワード一覧テーブルヘッダー %>
            <thead class="table_head">
              <tr>
                <th class="important_space">  </th>
                <th class="name_space">英単語</th>
                <th class="pos_space">品詞</th>
                <th class="meaning_space">和訳</th>
                <th class="genre_space">ジャンル</th>
                <th class="text_space">テキスト</th>
                <th class="publish_space"> 
                  <%= image_tag "publish_logo.png", class:"publish-pict" %>
                </th>
                <th class="good_space">
                  <%= image_tag "good_img.png", class:"good_image" %>
                  グー
                </th>
                <th class="recruitment_space">採用</th>
                <th class="btn_space">  </th>
              </tr>
            </thead>
            <%# ワード一覧表示 %>
            <tbody class ="table_scroll">
              <% if @words.present?%>
                <% @words.each do |word| %>
                  <tr>
                    <% if user_signed_in? && @user.id == current_user.id%>
                      <td class="important_space">
                        <%= best_in_place word, :important, :as => :select, collection: [[true, '★'], [false, '☆']] %>
                      </td>
                      <td class="name_space">
                        <%= best_in_place word, :name, :as => :input %>
                      </td>
                      <td class="pos_space">
                        <%= best_in_place word, :pos_id, :as => :select, collection: Pos.all.map{|pos| [pos.id, pos.name]} %>
                      </td>
                      <td class="meaning_space">
                        <%= best_in_place word, :meaning, :as => :input %>
                      </td>
                      <td class="genre_space">
                        <%= best_in_place word, :genre_id, :as => :select, collection: Genre.all.map{|genre| [genre.id, genre.name]} %>
                      </td>
                      <td class="text_space">
                        <%= best_in_place word, :text, :as => :input %>
                      </td>
                      <td class="publish_space">
                        <%= best_in_place word, :publish, :as => :select, collection: [[true, '○'], [false, '×']] %>
                      </td>
                      <td class="good_space"><%= word.goods.count %></td>
                      <td class="recruitment_space"> <%= word.adoptions.count %> </td>
                      <td class="btn_space"><%= link_to image_tag("bin.jpeg", class:"bin-btn"), word_path(word.id), method: :delete %></td>
                    <% else %>
                      <td class="important_space">
                        <% if word.important %>
                          ★
                        <% else %>
                          ☆
                        <% end %>
                      </td>
                      <td class="name_space"><%= word.name %></td>
                      <td class="pos_space"><%= word.pos.name %></td>
                      <td class="meaning_space"><%= word.meaning %></td>
                      <td class="genre_space"><%= word.genre.name %></td>
                      <td class="text_space"><%= word.text %></td>
                      <td class="publish_space">
                        <% if word.publish %>
                          ○
                        <% else %>
                          ×
                        <% end %>
                      </td>
                      <td class="good_space"><%= word.goods.count %></td>
                      <td class="recruitment_space"> <%= word.adoptions.count %> </td>
                      <td class="btn_space"><%= link_to "採用！", word_adoptions_path(word), method: :post , class:"recruitment-btn" %></td>
                    <% end %>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <%# サイドバー部分 %>
  <div class="side-bar">
    <div class="side-bar-contents">
      <div class="publish-users">
        <div class="sub-title">
          - ワード検索 -
        </div>
        <div class="try-test">
            <%= link_to "公開ワード検索", words_path, method: :get, class: "publish-btn"%>
        </div>
        <div class="list">〜最近グーしたワード〜
          <% if @good_words.present? %>
            <% @good_words.each do |word| %>
              <%= link_to word.name, user_path(word.user.id), class: "good_adoption_words"%>
            <% end %>
           <% else %>
            <p>※グーワードはありません</p>
          <% end %>
        </div>
        <div class="list">〜最近採用したワード〜
          <% if @adoption_words.present? %>
            <% @adoption_words.each do |word| %>
              <%= link_to word.name, user_path(word.user.id), class: "good_adoption_words"%>
            <% end %>
          <% else %>
            <p>※採用ワードはありません</p>
          <% end %>
        </div>
      </div>
      <% if user_signed_in? && @user.id == current_user.id %>
        <div class="test">
          <div class="sub-title">
            - テスト -
          </div>
          <div class="try-test">
            <% if @words.count >= 5 %>
              <%= form_with(model: @test, url: test_path(@user.id), local: true, method: :get, class: "test-link") do |form| %>
                <%= form.collection_select(:type_id, Type.all, :id, :name, {}, {class:"test-type-select-box", id:"test-type"}) %>
                <%= form.hidden_field :start_at, :value => nil %>
                <%= form.submit "テストを受ける", class: "test-btn" %>
              <% end %>
            <% else %>
              <div>５件以上ワード登録で<br>テスト機能利用可能！</div>
            <% end %>
          </div>
          <div class="test-result">
            <div class="sub-title"> - テスト結果 -</div>
            <%= month_calendar events: @tests do |date,tests|  %>
              <div class="calendar-day">
                <%= date.day %>
              </div>
              <div>
                <% tests.each do |test| %>
                  <%= link_to "●",result_test_path(test.id), method: :get %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>