config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "words#index"
  resources :users, only: :show

  resources :tests, only: [:show, :update] do
    resources :answers, only: :create
    member do
      get 'result'
    end
  end
  
  resources :words, only: [ :index, :create, :destroy, :edit, :update ] do
    resources :goods, only: [:create, :destroy]
    resources :adoptions, only: [:create, :destroy]
    
    member do
      get 'search_mydic'
    end

    collection do
      get 'search_index'
    end

    member do
      get 'order_mydic'
    end

    collection do
      get 'order_index'
    end
    
    collection do
      get 'weblio_pull'
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
  has_many :goods, dependent: :destroy
  has_many :good_users, through: :goods, source: :user
  has_many :adoptions, dependent: :destroy
  has_many :adoption_users, through: :adoptions, source: :user
  has_many :answers

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :pos
  belongs_to :genre

  with_options presence: true do
    validates  :name, :pos_id, :meaning, :genre_id
  end

  def self.search_mydic(search,condition,category,id)
    if search != ""
      if condition == "1" 
        if category == "1"
          Word.where('name LIKE(?) OR meaning LIKE(?) OR text LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%").where(user_id: id)
        elsif category == "2"
          Word.where('name LIKE(?)', "%#{search}%").where(user_id: id)
        elsif category == "3"
          Word.where('meaning LIKE(?)', "%#{search}%").where(user_id: id)
        elsif category == "4"
          Word.where('text LIKE(?)', "%#{search}%").where(user_id: id)
        end
      elsif condition == "2" 
        if category == "1"
          Word.where('name LIKE(?) OR meaning LIKE(?) OR text LIKE(?)', "#{search}%", "#{search}%", "#{search}%").where(user_id: id)
        elsif category == "2"
          Word.where('name LIKE(?)', "#{search}%").where(user_id: id)
        elsif category == "3"
          Word.where('meaning LIKE(?)', "#{search}%").where(user_id: id)
        elsif category == "4"
          Word.where('text LIKE(?)', "#{search}%").where(user_id: id)
        end
      end
    else
      Word.where(user_id: id)
    end
  end

  def self.search_index(search,condition,category)
    if search != ""
      if condition == "1" 
        if category == "1"
          Word.where('name LIKE(?) OR meaning LIKE(?) OR text LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
        elsif category == "2"
          Word.where('name LIKE(?)', "%#{search}%")
        elsif category == "3"
          Word.where('meaning LIKE(?)', "%#{search}%")
        elsif category == "4"
          Word.where('text LIKE(?)', "%#{search}%")
        end
      elsif condition == "2" 
        if category == "1"
          Word.where('name LIKE(?) OR meaning LIKE(?) OR text LIKE(?)', "#{search}%", "#{search}%", "#{search}%")
        elsif category == "2"
          Word.where('name LIKE(?)', "#{search}%")
        elsif category == "3"
          Word.where('meaning LIKE(?)', "#{search}%")
        elsif category == "4"
          Word.where('text LIKE(?)', "#{search}%")
        end
      end
    else
      Word.all
    end
  end

  def self.order_mydic(condition,id)
    if condition == "1" 
      Word.where(user_id: id).order(created_at: :desc)
    elsif condition == "2"
      Word.where(user_id: id).order(created_at: :asc)
    elsif condition == "3"
      Word.where(user_id: id).order(name: :asc)
    elsif condition == "4"
      Word.where(user_id: id).order(important: :desc)
    elsif condition == "5"
      Word.where(user_id: id).select('words.*', 'count(goods.id) AS goos').left_joins(:goods).group('words.id').order('goos desc')
    elsif condition == "6"
      Word.where(user_id: id).select('words.*', 'count(adoptions.id) AS ados').left_joins(:adoptions).group('words.id').order('ados desc')
    elsif condition == "7"
      Word.where(user_id: id).order(pos_id: :asc)
    elsif condition == "8"
      Word.where(user_id: id).order(genre_id: :asc)
    end
  end

  def self.order_index(condition)
    if condition == "1" 
      Word.order(created_at: :desc)
    elsif condition == "2"
      Word.order(created_at: :asc)
    elsif condition == "3"
      Word.order(name: :asc)
    elsif condition == "4"
      Word.select('words.*', 'count(goods.id) AS goos').left_joins(:goods).group('words.id').order('goos desc')
    elsif condition == "5"
      Word.select('words.*', 'count(adoptions.id) AS ados').left_joins(:adoptions).group('words.id').order('ados desc')
    elsif condition == "6"
      Word.order(pos_id: :asc)
    elsif condition == "7"
      Word.order(genre_id: :asc)
    end
  end

  def self.questions(id)
    ok_id=[]                                  #条件を満たしたWord情報のword_idを格納
    5.times do
      count = 0
      while count < 1
        last = Word.last.id                   #wordsテーブルに保存されている最後のword_idを取得
        num = rand(0..last)                   #ランダムに１件取得するようの"num"変数を用意
        word = Word.find_by('id >= ?', num)   #num変数以上のword_id情報の中で最初の１件を取得 ※削除機能により抜け番が発生するため
        if word != nil && word.user_id == id  #word!=nilは保険。word.user_id == id はcurrent_userが登録したword情報かを判別
          if ok_id.empty?                     #oK_id配列が空だったとき
            ok_id.push(word.id)                 #条件を満たすword_idをok_idに追加
            count = 1
          end
          unless ok_id.include?(word.id)      #oK_id配列に条件を満たすword_idを含まないとき ※テスト問題の一意性を出すため
            ok_id.push(word.id)                 #条件を満たすword_idをok_idに追加
            count = 1
          end
        end
      end
    end
    words = Word.where(id: ok_id)             #条件をクリアした５件のword_idが格納されたok_idをword_idにもつwordを"words"に格納する
    return words
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :destroy, :update, :search_mydic, :search_index, :order_mydic, :order_index]
  before_action :set_data,only: [:search_mydic, :order_mydic]

  def index
    @words = Word.where(publish: true)
    @good = Good.new
  end

  def create
    @word = Word.create(word_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to user_path(current_user.id)
  end

  def update
    @word = Word.find(params[:id])
    if  @word.update(word_params)
      redirect_to user_path(current_user.id)
    else
      render "users/show"
    end
  end

  def search_mydic
    @words = Word.search_mydic(params[:keyword], params[:condition], params[:category], params[:id])
    render "users/show"
  end

  def search_index
    @words = Word.search_index(params[:keyword], params[:condition], params[:category])
    render :index
  end

  def order_mydic
    @words = Word.order_mydic(params[:condition], params[:id])
    render "users/show"
  end

  def order_index
    @words = Word.order_index(params[:condition])
    render :index
  end

  def weblio_pull
    lib_url='https://ejje.weblio.jp/content/'.freeze
    xpath="//*[@id=\"summary\"]/div[2]/table/tbody/tr/td[2]".freeze

    if params[:name].blank?
      render json: { error: '※検索ワードを入れてください。' } and return 
      return
    end

    url = URI.encode(lib_url + params[:name])
    html = URI.open(url).read
    doc = Nokogiri::HTML.parse(html)
    result = doc.xpath(xpath).text
    if result.blank?
      render json: { error: '※一致する見出し語は見つかりませんでした。' } and return  
    else
      render json:{ result: result } 
    end
  end

  private
  def set_data
    @user = User.find(params[:id])
    @word = Word.new
    @good_words = @user.good_words.order(created_at: :desc).limit(5)
    @adoption_words = @user.adoption_words.order(created_at: :desc).limit(5)
    @test = Test.new
    @tests = Test.where(user_id: current_user.id)
  end
  
  def word_params
    params.require(:word).permit(:important, :name, :pos_id, :meaning, :genre_id, :text, :publish).merge(user_id: current_user.id)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/index.html.erb
<%= render "devise/shared/header" %>

<div class="publish-main">
  <div class="publish-word-index">
    <div class="word-index-header">
      <h3> - 公開ワード  一覧 - </h3>
      <div class="word-index-header-right">
        <div class="word-search">
          <%= form_with(url: search_index_words_path, local: true, method: :get, class: "word-search") do |form| %>
              <%= form.text_field :keyword, placeholder: "検索ワード入力", class: "search-input" %>
              <%= form.select :condition, [['を含む', 1], ['から始まる', 2]] %>
              <%= form.select :category, [['全て', 1],['英単語', 2], ['和訳', 3], ['テキスト', 4]] %>
              <div>を</div>
              <%= form.submit "検索", class: "search-btn" %>
            <% end %>
        </div>
        <div class="index-sort">
          <%= form_with(url: order_index_words_path, local: true, method: :get, class: "word-search") do |form| %>
            <%= form.select :condition, [['登録新しい順', 1], ['登録古い順', 2], ['英単語ｱﾙﾌｧﾍﾞｯﾄ順', 3], ['グー数多い順', 4], ['採用数多い順', 5], ['品詞順', 6], ['ジャンル順', 7]] %>
            <%= form.submit "並び替え", class: "search-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="word-index-data">
      <div class="word-contents">
        <table class="publish_index_table">
          <thead class="table_head">
            <tr>
              <th class="user_nickname_space">投稿者</th>
              <th class="publish_name_space">英単語</th>
              <th class="publish_pos_space">品詞</th>
              <th class="publish_meaning_space">和訳</th>
              <th class="publish_genre_space">ジャンル</th>
              <th class="publish_text_space">テキスト</th>
              <th class="publish_good_space">
                <%= image_tag "good_img.png", class:"good_image" %>
                グー
              </th>
              <th class="publish_recruitment_space">採用</th>
              <th class="publish_btn_space">  </th>
            </tr>
          </thead>
          <tbody class="publish_table_scroll">
            <% @words.each do |word| %>
              <tr>
                <td class="user_nickname_space"><%= link_to word.user.nickname, user_path(word.user_id) %></td>
                <td class="publish_name_space"><%= word.name %></td>
                <td class="publish_pos_space"><%= word.pos.name %></td>
                <td class="publish_meaning_space"><%= word.meaning %></td>
                <td class="publish_genre_space"><%= word.genre.name %></td>
                <td class="publish_text_space"><%= word.text %></td>
                <td class="publish_good_space">
                  <% if user_signed_in? && current_user.id != word.user_id %>
                    <% if current_user&.good?(word) %>
                      <%= link_to image_tag("good_img.png", class:"good_image"), word_good_path(word.id,Good.find_by(word_id: word.id, user_id: current_user.id)), method: :delete %>
                    <% else %>
                      <%= link_to image_tag("ungood_img.png", class:"good_image"),word_goods_path(word), method: :post %>
                    <% end %>
                  <% else %>
                    <%= image_tag("good_img.png", class:"good_image") %>
                  <% end %>
                  <%= word.goods.count %>
                </td>
                <td class="publish_recruitment_space"><%= word.adoptions.count %></td>
                <td class="publish_btn_space">
                  <% if current_user.id != word.user_id %>
                    <%= link_to "採用！", word_adoptions_path(word), method: :post %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>